### ISSUE TITLE
Docker image size calculated using compressed layer sizes

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry/garden-shed#8]
As far as I can tell, docker image sizes are calculated by summing the image layer sizes, and image layer sizes are pulled from the docker registry api at https://github.com/cloudfoundry/garden-shed/blob/master/distclient/client.go#L70. But image layer sizes returned by the api are given in compressed bytes. That means the volume size for docker images gets underestimated. We noticed this issue when we switched to grootfs, which appears to calculate image sizes correctly, and an image that previously fit within its quota suddenly registered as too large.

cc @julz @sharms @wjwoodson

**Comment by julz** [comment]
I strongly suspect you're right @jmcarp however since we've now deprecated garden-shed I don't think it makes sense for us to prioritise work to change this behaviour now. I also don't _think_ it would make sense to revert grootfs to the old, wrong, behaviour which gave you more space than your quota really allowed. My understanding is the new grootfs code, which everyone will get when they next upgrade, does the right thing, so I think this is resolved for us now. Thanks for digging in to this and figuring out what happened!
